// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjNGFNsB2Iei_PvcCAtb5QbTpuxh1rPYU',
    appId: '1:189702624880:web:da4d895ab31e033d8786b5',
    messagingSenderId: '189702624880',
    projectId: 'ecoaware-7da17',
    authDomain: 'ecoaware-7da17.firebaseapp.com',
    storageBucket: 'ecoaware-7da17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv0lBIaPm_FQkk9tVa4d74tLjg7jmJCW0',
    appId: '1:189702624880:android:9f924168daf866248786b5',
    messagingSenderId: '189702624880',
    projectId: 'ecoaware-7da17',
    storageBucket: 'ecoaware-7da17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDys8WvBn-eFKzr5AJyZPqWOrp5ltH16Vc',
    appId: '1:189702624880:ios:2f2322eb110f2b0a8786b5',
    messagingSenderId: '189702624880',
    projectId: 'ecoaware-7da17',
    storageBucket: 'ecoaware-7da17.appspot.com',
    iosBundleId: 'com.example.ecoaware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDys8WvBn-eFKzr5AJyZPqWOrp5ltH16Vc',
    appId: '1:189702624880:ios:2f2322eb110f2b0a8786b5',
    messagingSenderId: '189702624880',
    projectId: 'ecoaware-7da17',
    storageBucket: 'ecoaware-7da17.appspot.com',
    iosBundleId: 'com.example.ecoaware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjNGFNsB2Iei_PvcCAtb5QbTpuxh1rPYU',
    appId: '1:189702624880:web:d6d2f947eb18b2ac8786b5',
    messagingSenderId: '189702624880',
    projectId: 'ecoaware-7da17',
    authDomain: 'ecoaware-7da17.firebaseapp.com',
    storageBucket: 'ecoaware-7da17.appspot.com',
  );
}
